<?php
/**
 * Public Landing-Page Domain — mapping infrastructure.
 *
 * Lets the lead-page post type publish on a separate public domain (e.g.
 * go.21stcenturylending.com) that can differ from the WordPress/subsite domain,
 * WITHOUT exposing the rest of the site on that domain.
 *
 * This class owns the infrastructure: the admin-configurable mapping, a tiny
 * generated map file that the early-loading sunrise drop-in reads (no DB that
 * early), and a managed block inside wp-content/sunrise.php. The request-time
 * URL/route rewriting lives in {@see PublicDomain}.
 *
 * It is intentionally generic: it maps whatever domain is configured to the blog
 * that hosts the lead pages, regardless of what domain the site itself runs on.
 *
 * @package FRSLeadPages
 */

namespace FRSLeadPages\Core;

defined( 'ABSPATH' ) || exit;

class DomainMapping {

	/** Settings (stored on the blog that hosts the lead pages). */
	const OPT_ENABLED = 'frs_lead_pages_public_domain_enabled';
	const OPT_DOMAIN  = 'frs_lead_pages_public_domain';
	const OPT_BLOG    = 'frs_lead_pages_public_blog';

	/** Managed-block markers inside wp-content/sunrise.php. */
	const SUNRISE_BEGIN = '// BEGIN frs-lead-pages public domain';
	const SUNRISE_END   = '// END frs-lead-pages public domain';

	/**
	 * Hook the sync routine to settings changes.
	 *
	 * @return void
	 */
	public static function init(): void {
		foreach ( [ self::OPT_ENABLED, self::OPT_DOMAIN ] as $opt ) {
			add_action( 'add_option_' . $opt, [ __CLASS__, 'sync' ] );
			add_action( 'update_option_' . $opt, [ __CLASS__, 'sync' ] );
		}
	}

	/**
	 * Absolute path to the generated map file the sunrise drop-in reads.
	 *
	 * @return string
	 */
	public static function map_file(): string {
		return WP_CONTENT_DIR . '/frs-lead-pages-domain-map.php';
	}

	/**
	 * Absolute path to the shared multisite sunrise drop-in.
	 *
	 * @return string
	 */
	public static function sunrise_file(): string {
		return WP_CONTENT_DIR . '/sunrise.php';
	}

	/**
	 * Is the public-domain mapping enabled?
	 *
	 * @return bool
	 */
	public static function is_enabled(): bool {
		return (bool) get_option( self::OPT_ENABLED, false );
	}

	/**
	 * Configured public-domain host (lowercased, no scheme or trailing slash),
	 * or '' when not configured.
	 *
	 * @return string
	 */
	public static function get_host(): string {
		$domain = trim( (string) get_option( self::OPT_DOMAIN, '' ) );
		if ( $domain === '' ) {
			return '';
		}
		if ( ! preg_match( '#^https?://#i', $domain ) ) {
			$domain = 'https://' . $domain;
		}
		return strtolower( (string) wp_parse_url( $domain, PHP_URL_HOST ) );
	}

	/**
	 * Blog that hosts the lead pages. Falls back to the current blog.
	 *
	 * @return int
	 */
	public static function get_blog_id(): int {
		$blog = (int) get_option( self::OPT_BLOG, 0 );
		return $blog > 0 ? $blog : (int) get_current_blog_id();
	}

	/**
	 * Rebuild the map file + sunrise block from the current settings.
	 * Idempotent and safe to call repeatedly.
	 *
	 * @return void
	 */
	public static function sync(): void {
		// Remember which blog owns the lead pages (the one being configured).
		if ( (int) get_option( self::OPT_BLOG, 0 ) === 0 ) {
			update_option( self::OPT_BLOG, (int) get_current_blog_id() );
		}

		if ( self::is_enabled() && self::get_host() !== '' && is_multisite() ) {
			self::write_map_file();
			self::install_sunrise_block();
		} else {
			self::remove_map_file();
			self::remove_sunrise_block();
		}
	}

	/**
	 * Write the generated map file the sunrise drop-in reads.
	 *
	 * @return bool
	 */
	private static function write_map_file(): bool {
		$network = get_network();

		$map = [
			'enabled' => true,
			'host'    => self::get_host(),
			'blog_id' => self::get_blog_id(),
			'site_id' => $network ? (int) $network->id : 1,
		];

		$contents = "<?php\n"
			. "// Generated by frs-lead-pages. Do not edit by hand.\n"
			. 'return ' . var_export( $map, true ) . ";\n";

		return self::atomic_put( self::map_file(), $contents );
	}

	/**
	 * Remove the generated map file.
	 *
	 * @return void
	 */
	private static function remove_map_file(): void {
		$file = self::map_file();
		if ( file_exists( $file ) ) {
			@unlink( $file );
		}
	}

	/**
	 * Ensure wp-content/sunrise.php includes the plugin's sunrise drop-in.
	 * Only manages its own marked block; never touches other plugins' blocks.
	 *
	 * @return bool
	 */
	private static function install_sunrise_block(): bool {
		$file = self::sunrise_file();

		$existing = file_exists( $file ) ? (string) file_get_contents( $file ) : "<?php\n";
		if ( strpos( $existing, '<?php' ) === false ) {
			$existing = "<?php\n" . $existing;
		}

		// Strip any previous block, then append a fresh one.
		$existing = self::strip_block( $existing );

		$plugin_sunrise = FRS_LEAD_PAGES_PLUGIN_DIR . 'sunrise.php';
		$block          = "\n" . self::SUNRISE_BEGIN . "\n"
			. "if ( file_exists( '" . addslashes( $plugin_sunrise ) . "' ) ) {\n"
			. "\tinclude_once '" . addslashes( $plugin_sunrise ) . "';\n"
			. "}\n"
			. self::SUNRISE_END . "\n";

		return self::atomic_put( $file, rtrim( $existing, "\n" ) . "\n" . $block );
	}

	/**
	 * Remove the plugin's managed block from wp-content/sunrise.php.
	 *
	 * @return void
	 */
	private static function remove_sunrise_block(): void {
		$file = self::sunrise_file();
		if ( ! file_exists( $file ) ) {
			return;
		}
		$contents = (string) file_get_contents( $file );
		if ( strpos( $contents, self::SUNRISE_BEGIN ) === false ) {
			return;
		}
		self::atomic_put( $file, self::strip_block( $contents ) );
	}

	/**
	 * Remove the plugin's marked block (if present) from sunrise contents.
	 *
	 * @param string $contents File contents.
	 * @return string
	 */
	private static function strip_block( string $contents ): string {
		$pattern = '/\n?' . preg_quote( self::SUNRISE_BEGIN, '/' ) . '.*?' . preg_quote( self::SUNRISE_END, '/' ) . "\n?/s";
		return (string) preg_replace( $pattern, "\n", $contents );
	}

	/**
	 * Write a file atomically (temp file + rename) so a partial write can never
	 * leave a broken sunrise.php / map file in place.
	 *
	 * @param string $path     Destination path.
	 * @param string $contents File contents.
	 * @return bool
	 */
	private static function atomic_put( string $path, string $contents ): bool {
		$dir = dirname( $path );
		if ( ! is_writable( $dir ) && ! ( file_exists( $path ) && is_writable( $path ) ) ) {
			return false;
		}
		$tmp = $path . '.tmp-' . wp_generate_password( 8, false );
		if ( false === file_put_contents( $tmp, $contents ) ) { // phpcs:ignore WordPress.WP.AlternativeFunctions.file_system_operations_file_put_contents
			@unlink( $tmp );
			return false;
		}
		if ( ! @rename( $tmp, $path ) ) {
			@unlink( $tmp );
			return false;
		}
		return true;
	}

	/**
	 * Human-readable readiness status for the admin screen.
	 *
	 * @return array{ready:bool,sunrise_constant:bool,sunrise_block:bool,map_file:bool,notes:string[]}
	 */
	public static function status(): array {
		$notes            = [];
		$sunrise_constant = defined( 'SUNRISE' ) && SUNRISE;
		$sunrise_block    = file_exists( self::sunrise_file() )
			&& strpos( (string) file_get_contents( self::sunrise_file() ), self::SUNRISE_BEGIN ) !== false;
		$map_file         = file_exists( self::map_file() );

		if ( ! is_multisite() ) {
			$notes[] = __( 'This site is not multisite; the domain just needs DNS pointed at it (no sunrise mapping required).', 'frs-lead-pages' );
		}
		if ( is_multisite() && ! $sunrise_constant ) {
			$notes[] = __( "Add define( 'SUNRISE', true ); to wp-config.php (above the \"stop editing\" line) so the mapping can load.", 'frs-lead-pages' );
		}

		return [
			'ready'            => $sunrise_constant && $sunrise_block && $map_file,
			'sunrise_constant' => $sunrise_constant,
			'sunrise_block'    => $sunrise_block,
			'map_file'         => $map_file,
			'notes'            => $notes,
		];
	}

	/**
	 * Tear down all generated artifacts (used on deactivation).
	 *
	 * @return void
	 */
	public static function teardown(): void {
		self::remove_map_file();
		self::remove_sunrise_block();
	}
}
